import { defineConfig } from 'oxfmt';

export default defineConfig({
  printWidth: 80,
  sortPackageJson: true,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  endOfLine: 'lf',
  bracketSameLine: true,
  insertFinalNewline: true,
  ignorePatterns: [
    '**/node_modules/**',
    'dist/**',
    'examples/**',
    'docs/.vitepress/cache/**',
    'docs/.vitepress/dist/**',
    'graphify-out/**',
    // Generated by scripts/bench/run.ts — reformatting fights the generator.
    'benchmarks/**',
  ],
});
