/** `.d.typeflow.ts` declaration emission. */
import { type CompileResult } from './index';
import { typeToString } from '#core';

export interface EmitDtsOptions {
  sourceFileName?: string;
}

/**
 * Emit a `.d.typeflow.ts` declaration file. With `allowArbitraryExtensions` enabled,
 * TypeScript resolves `import mapper from "./user.typeflow"` against `user.d.typeflow.ts`.
 */
export function emitDts(
  result: CompileResult,
  options: EmitDtsOptions = {},
): string {
  const input = result.inputType ? typeToString(result.inputType) : 'unknown';
  const output = result.outputType
    ? typeToString(result.outputType)
    : 'unknown';
  const from = options.sourceFileName ? ` from ${options.sourceFileName}` : '';
  return [
    `// Generated by Typeflow${from}. Do not edit.`,
    ``,
    `type TypeflowInput = ${input};`,
    ``,
    `type TypeflowOutput = ${output};`,
    ``,
    `declare const mapping: (input: TypeflowInput) => TypeflowOutput;`,
    ``,
    `export type { TypeflowInput as Input, TypeflowOutput as Output };`,
    `export default mapping;`,
    ``,
  ].join('\n');
}
