import {
  makeUnion,
  T,
  typeToString,
  type CompiledMapping,
  type Diagnostic,
  type MappingFile,
  type Type,
  type TypeNode,
} from "@thomasfarineau/typeflow-core";
import { parse } from "@thomasfarineau/typeflow-parser";
import { Checker } from "./checker.ts";

export { BUILTINS } from "./builtins.ts";

export interface ResolveTypeRequest {
  typeName: string;
  from: string;
  /** Absolute path of the `.typeflow` file, when known — used to resolve relative module paths. */
  filePath?: string;
}

export type TypeResolver = (req: ResolveTypeRequest) => { type: Type } | { error: string };

export interface CompileOptions {
  fileName?: string;
  filePath?: string;
  resolveType?: TypeResolver;
}

export interface CompileResult {
  ok: boolean;
  diagnostics: Diagnostic[];
  ast: MappingFile | null;
  inputName: string | null;
  inputType: Type | null;
  outputType: Type | null;
  /** Serializable runtime artifact; present whenever the file parses. */
  compiled: CompiledMapping | null;
}

export function compile(source: string, options: CompileOptions = {}): CompileResult {
  const diagnostics: Diagnostic[] = [];
  const { ast, diagnostics: parseDiagnostics } = parse(source);
  diagnostics.push(...parseDiagnostics);

  if (!ast) {
    return { ok: false, diagnostics, ast: null, inputName: null, inputType: null, outputType: null, compiled: null };
  }

  let inputName = "input";
  let inputType: Type = T.any;

  if (!ast.input) {
    diagnostics.push({
      code: "TF2015",
      message: "No 'input' declaration: the input is typed as 'any' and paths cannot be validated.",
      span: ast.map.span,
      severity: "warning",
      hint: 'Declare one, e.g.: input user: User from "./types"',
    });
  } else {
    inputName = ast.input.name;
    if (ast.input.inlineType) {
      inputType = typeFromNode(ast.input.inlineType);
    } else if (ast.input.typeRef) {
      const { typeName, from } = ast.input.typeRef;
      if (!options.resolveType) {
        diagnostics.push({
          code: "TF2010",
          message: `Cannot resolve type '${typeName}' from '${from}': no schema adapter is configured.`,
          span: ast.input.span,
          severity: "error",
        });
      } else {
        const resolved = options.resolveType({ typeName, from, filePath: options.filePath });
        if ("error" in resolved) {
          diagnostics.push({
            code: "TF2010",
            message: `Cannot resolve type '${typeName}' from '${from}': ${resolved.error}`,
            span: ast.input.span,
            severity: "error",
          });
        } else {
          inputType = resolved.type;
        }
      }
    }
  }

  const checker = new Checker(diagnostics);
  const outputType = checker.checkMapping(ast.map, inputName, inputType);

  const compiled: CompiledMapping = { version: 1, inputName, ir: ast.map };
  const ok = !diagnostics.some((d) => d.severity === "error");

  return { ok, diagnostics, ast, inputName, inputType, outputType, compiled };
}

export function typeFromNode(node: TypeNode): Type {
  switch (node.kind) {
    case "prim":
      switch (node.name) {
        case "string": return T.string;
        case "number": return T.number;
        case "boolean": return T.boolean;
        case "null": return T.null;
        case "unknown": return T.unknown;
      }
      break;
    case "lit":
      return T.literal(node.value);
    case "array":
      return T.array(typeFromNode(node.element));
    case "object":
      return T.object(
        node.fields.map((f) => ({ name: f.name, type: typeFromNode(f.type), optional: f.optional })),
      );
    case "union":
      return makeUnion(node.types.map(typeFromNode));
  }
}

export interface EmitDtsOptions {
  sourceFileName?: string;
}

/**
 * Emit a `.d.typeflow.ts` declaration file. With `allowArbitraryExtensions` enabled,
 * TypeScript resolves `import mapper from "./user.typeflow"` against `user.d.typeflow.ts`.
 */
export function emitDts(result: CompileResult, options: EmitDtsOptions = {}): string {
  const input = result.inputType ? typeToString(result.inputType) : "unknown";
  const output = result.outputType ? typeToString(result.outputType) : "unknown";
  const from = options.sourceFileName ? ` from ${options.sourceFileName}` : "";
  return [
    `// Generated by Typeflow${from}. Do not edit.`,
    ``,
    `type TypeflowInput = ${input};`,
    ``,
    `type TypeflowOutput = ${output};`,
    ``,
    `declare const mapping: (input: TypeflowInput) => TypeflowOutput;`,
    ``,
    `export type { TypeflowInput as Input, TypeflowOutput as Output };`,
    `export default mapping;`,
    ``,
  ].join("\n");
}
