// Value imports from the library go through the package name: Vite's config
// bundler externalizes them, and Node then resolves the export map to the
// built dist/index.js (docs:dev / docs:build run `bun scripts/build.ts`
// first). Importing ../../src here instead would make Node load the raw
// TypeScript sources at config time, where the runtime `#core`-style subpath
// imports and extensionless relative imports don't resolve.
import { type DefaultTheme, defineConfig } from 'vitepress';
import { readdirSync, readFileSync } from 'node:fs';
import { type Builtin } from '../../src/builtins/types';
import { BUILTIN_GROUPS } from 'typeflow-js';
import container from 'markdown-it-container';
import { DOC_PAGES } from '../../scripts/doc-pages';
import { fileURLToPath } from 'node:url';
import { FR_FUNCTION_GROUPS } from '../../scripts/doc-pages/i18n/fr-functions';
import { highlightTypeflow } from './theme/highlight';
import { join } from 'node:path';
import type MarkdownIt from 'markdown-it';

type Locale = 'en' | 'fr';
const prefix = (locale: Locale) => (locale === 'fr' ? '/fr' : '');

const pkg = (name: string) =>
  fileURLToPath(new URL(`../../src/${name}/index.ts`, import.meta.url));

function slug(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Groups functions sharing a `category` into contiguous runs, in source order. */
function categoryRuns(
  entries: [string, Builtin][],
): { category: string; entries: [string, Builtin][] }[] {
  const runs: { category: string; entries: [string, Builtin][] }[] = [];
  for (const entry of entries) {
    const category = entry[1].category ?? '';
    const last = runs.at(-1);
    if (last && last.category === category) last.entries.push(entry);
    else runs.push({ category, entries: [entry] });
  }
  return runs;
}

/**
 * A third sidebar level: opening "Strings" (or "Arithmetic & strings") shows
 * its categories/operators as sub-items linking straight to their anchor —
 * one more click level saved, same source of truth as the generator.
 */
function subItemsFor(
  section: string,
  pageId: string,
  locale: Locale,
): DefaultTheme.SidebarItem[] | undefined {
  // Sidebar item text is rendered with v-html — sub-items get styled chips
  // (see .sb-op / .sb-count in theme/custom.css) instead of raw text.
  if (section === 'operators') {
    const page = DOC_PAGES.find((p) => p.id === pageId);
    if (!page) return undefined;
    return page.items.map((item) => ({
      text: `<code class="sb-op">${escapeHtml(item.name)}</code>`,
      link: `${prefix(locale)}/operators/${pageId}#${item.id}`,
    }));
  }
  if (section === 'functions') {
    const group = BUILTIN_GROUPS.find((g) => g.id === pageId);
    if (!group) return undefined;
    const entries = Object.entries(group.functions);
    if (!entries.some(([, b]) => b.category)) return undefined;
    return categoryRuns(entries).map((run) => {
      // Anchors always use the English category slug (same in both locales);
      // only the visible label is translated.
      const label =
        locale === 'fr'
          ? (FR_FUNCTION_GROUPS[pageId]?.categories?.[run.category] ??
            run.category)
          : run.category;
      return {
        text: `${escapeHtml(label)}<span class="sb-count">${run.entries.length}</span>`,
        link: `${prefix(locale)}/functions/${pageId}#${pageId}-${slug(run.category)}`,
      };
    });
  }
  return undefined;
}

/**
 * Generated sidebar sections: docs/<section>/*.md are scanned for their h1
 * (title) and `order` frontmatter (position). The pages themselves are
 * generated by scripts/generate-docs.ts — nothing to update here.
 */
function generatedSidebar(
  section: string,
  locale: Locale = 'en',
): DefaultTheme.SidebarItem[] {
  const dir = fileURLToPath(
    new URL(
      locale === 'fr' ? `../fr/${section}` : `../${section}`,
      import.meta.url,
    ),
  );
  const base = `${prefix(locale)}/${section}`;
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const source = readFileSync(join(dir, f), 'utf8');
      const order = Number(/^order:\s*(\d+)/m.exec(source)?.[1] ?? 999);
      const title = /^#\s+(.+?)(?:\s*\{#.*\})?\s*$/m.exec(source)?.[1] ?? f;
      const pageId = f.replace(/\.md$/, '');
      const items =
        pageId === 'index' ? undefined : subItemsFor(section, pageId, locale);
      return {
        order,
        text: title,
        link: pageId === 'index' ? `${base}/` : `${base}/${pageId}`,
        items,
        collapsed: items ? true : undefined,
      };
    })
    .toSorted((a, b) => a.order - b.order)
    .map(({ text, link, items, collapsed }) => ({
      text,
      link,
      items,
      collapsed,
    }));
}

/**
 * Standalone ```typeflow fences (outside `::: playground`) are static — Shiki
 * has no `typeflow` grammar, and aliasing to a real one (e.g. `typescript`)
 * renders with that language's generic color theme, which doesn't match the
 * site's own token colors used by the live playground (tok-* in tokens.css).
 * Render these with the same real tokenizer instead, so static snippets and
 * live playgrounds look identical.
 */
function typeflowFence(md: MarkdownIt): void {
  const defaultFence = md.renderer.rules.fence!.bind(md.renderer.rules);
  md.renderer.rules.fence = (tokens, idx, options, env, self) => {
    const token = tokens[idx]!;
    if (token.info.trim() !== 'typeflow') {
      return defaultFence(tokens, idx, options, env, self);
    }
    const code = highlightTypeflow(token.content.replace(/\n$/, ''));
    return `<div class="language-typeflow"><button title="Copy Code" class="copy"></button><span class="lang">typeflow</span><pre class="tf-code" tabindex="0"><code>${code}</code></pre></div>\n`;
  };
}

/**
 * `::: playground` container: collects the `typeflow` and `json` fences inside it
 * and renders a <MiniPlayground> instead — live, editable examples inside doc pages.
 */
function playgroundContainer(md: MarkdownIt): void {
  md.use(container, 'playground', {
    render(tokens: any[], idx: number): string {
      const token = tokens[idx];
      if (token.nesting !== 1) return '';
      let mapping = '';
      let input = '';
      for (let i = idx + 1; i < tokens.length; i++) {
        const t = tokens[i];
        if (t.type === 'container_playground_close') break;
        if (t.type === 'fence') {
          if (t.info.trim() === 'json') input = t.content;
          else mapping = t.content;
          // Swallow the fence: the component renders the code instead.
          t.type = 'html_block';
          t.content = '';
        }
      }
      return `<MiniPlayground mapping="${encodeURIComponent(mapping)}" input="${encodeURIComponent(input)}" />\n`;
    },
  });
}

const SITE = 'https://thomasfarineau.github.io/typeflow/';

export default defineConfig({
  title: 'Typeflow',
  description: 'Typed JSON transformations, checked at compile time.',
  base: '/typeflow/',
  lastUpdated: true,
  sitemap: { hostname: SITE },
  head: [
    [
      'link',
      { rel: 'icon', type: 'image/svg+xml', href: '/typeflow/logo.svg' },
    ],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:site_name', content: 'Typeflow' }],
    ['meta', { property: 'og:image', content: `${SITE}logo.svg` }],
    ['meta', { name: 'twitter:card', content: 'summary' }],
  ],
  // hreflang alternates: every page advertises its EN and FR counterparts.
  transformHead({ pageData }) {
    const rel = pageData.relativePath
      .replace(/(^|\/)index\.md$/, '$1')
      .replace(/\.md$/, '');
    const enPath = rel.replace(/^fr(\/|$)/, '');
    return [
      ['link', { rel: 'alternate', hreflang: 'en', href: `${SITE}${enPath}` }],
      [
        'link',
        { rel: 'alternate', hreflang: 'fr', href: `${SITE}fr/${enPath}` },
      ],
    ];
  },
  locales: {
    root: {
      label: 'English',
      lang: 'en',
    },
    fr: {
      label: 'Français',
      lang: 'fr',
      link: '/fr/',
      description: 'Transformations JSON typées, vérifiées à la compilation.',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/fr/guide/getting-started' },
          {
            text: 'Référence',
            items: [
              { text: 'Opérateurs', link: '/fr/operators/literals' },
              { text: 'Fonctions', link: '/fr/functions/' },
              { text: 'Diagnostics', link: '/fr/reference/diagnostics' },
            ],
          },
          { text: 'Playground', link: '/fr/playground' },
          { text: 'Benchmark', link: '/fr/benchmark' },
        ],
        sidebar: [
          {
            text: 'Guide',
            items: [
              { text: 'Bien démarrer', link: '/fr/guide/getting-started' },
              { text: 'Le langage', link: '/fr/guide/language' },
              { text: 'CLI', link: '/fr/guide/cli' },
            ],
          },
          {
            text: 'Opérateurs',
            items: generatedSidebar('operators', 'fr'),
          },
          {
            text: 'Fonctions',
            items: generatedSidebar('functions', 'fr'),
          },
          {
            text: 'Référence',
            items: generatedSidebar('reference', 'fr'),
          },
          {
            text: 'Playground',
            items: [
              { text: 'Essayer en direct', link: '/fr/playground' },
              { text: 'Benchmark', link: '/fr/benchmark' },
              { text: 'Rapports de benchmark', link: '/benchmarks/' },
            ],
          },
        ],
        outline: { label: 'Sur cette page', level: [2, 4] },
        editLink: {
          pattern:
            'https://github.com/thomasfarineau/typeflow/edit/main/docs/:path',
          text: 'Modifier cette page sur GitHub',
        },
        lastUpdated: { text: 'Mis à jour' },
        docFooter: { prev: 'Page précédente', next: 'Page suivante' },
        darkModeSwitchLabel: 'Apparence',
        sidebarMenuLabel: 'Menu',
        returnToTopLabel: 'Retour en haut',
        langMenuLabel: 'Changer de langue',
        footer: {
          message: 'Publié sous licence MIT.',
          copyright: 'Copyright © 2026 Thomas Farineau',
        },
      },
    },
  },
  themeConfig: {
    logo: '/logo.svg',
    outline: { level: [2, 4] },
    editLink: {
      pattern:
        'https://github.com/thomasfarineau/typeflow/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
    search: {
      provider: 'local',
      options: {
        locales: {
          fr: {
            translations: {
              button: {
                buttonText: 'Rechercher',
                buttonAriaLabel: 'Rechercher',
              },
              modal: {
                displayDetails: 'Afficher les détails',
                resetButtonTitle: 'Effacer la recherche',
                backButtonTitle: 'Fermer',
                noResultsText: 'Aucun résultat pour',
                footer: {
                  selectText: 'pour sélectionner',
                  navigateText: 'pour naviguer',
                  closeText: 'pour fermer',
                },
              },
            },
          },
        },
      },
    },
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      {
        text: 'Reference',
        items: [
          { text: 'Operators', link: '/operators/literals' },
          { text: 'Functions', link: '/functions/' },
          { text: 'Diagnostics', link: '/reference/diagnostics' },
        ],
      },
      { text: 'Playground', link: '/playground' },
      { text: 'Benchmark', link: '/benchmark' },
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting started', link: '/guide/getting-started' },
          { text: 'The language', link: '/guide/language' },
          { text: 'CLI', link: '/guide/cli' },
        ],
      },
      {
        text: 'Operators',
        items: generatedSidebar('operators'),
      },
      {
        text: 'Functions',
        items: generatedSidebar('functions'),
      },
      {
        text: 'Reference',
        items: generatedSidebar('reference'),
      },
      {
        text: 'Playground',
        items: [
          { text: 'Try it live', link: '/playground' },
          { text: 'Benchmark', link: '/benchmark' },
          { text: 'Benchmark reports', link: '/benchmarks/' },
        ],
      },
    ],
    socialLinks: [
      { icon: 'github', link: 'https://github.com/thomasfarineau/typeflow' },
    ],
    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright © 2026 Thomas Farineau',
    },
  },
  markdown: {
    config: (md) => {
      typeflowFence(md);
      playgroundContainer(md);
    },
  },
  vite: {
    resolve: {
      // The playground imports the compiler by its old per-package names; map them to src/.
      alias: {
        '@thomasfarineau/typeflow-core': pkg('core'),
        '@thomasfarineau/typeflow-parser': pkg('parser'),
        '@thomasfarineau/typeflow-formatter': pkg('formatter'),
        '@thomasfarineau/typeflow-compiler': pkg('compiler'),
        '@thomasfarineau/typeflow-runtime': pkg('runtime'),
      },
    },
    ssr: {
      // Workspace packages ship TypeScript source; bundle them during SSR build.
      noExternal: [/@thomasfarineau\/typeflow/],
    },
  },
});
