/**
 * Publishes benchmarks/<date>/ reports into the docs site.
 *
 * Copies every benchmarks/<YYYY-MM-DD>/ directory (result.md renamed to
 * index.md, plus its SVG charts and results.json) to docs/benchmarks/<date>/,
 * and generates docs/benchmarks/index.md listing every run, newest first.
 * docs/benchmarks/ is generated output (gitignored), like the pages produced
 * by scripts/generate-docs.ts — the source of truth stays in benchmarks/.
 *
 * Run with: bun scripts/bench/publish.ts (or bun run bench:publish)
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

const root = join(import.meta.dir, '../..');
const srcDir = join(root, 'benchmarks');
const outDir = join(root, 'docs', 'benchmarks');

if (!existsSync(srcDir)) {
  console.error(
    'Nothing to publish: benchmarks/ does not exist. Run `bun run bench` first.',
  );
  process.exit(1);
}

const runs = readdirSync(srcDir, { withFileTypes: true })
  .filter((e) => e.isDirectory() && /^\d{4}-\d{2}-\d{2}$/.test(e.name))
  .map((e) => e.name)
  .filter((date) => existsSync(join(srcDir, date, 'result.md')))
  .toSorted()
  .toReversed();

if (runs.length === 0) {
  console.error(
    'Nothing to publish: no benchmarks/<date>/result.md found. Run `bun run bench` first.',
  );
  process.exit(1);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const date of runs) {
  const from = join(srcDir, date);
  const to = join(outDir, date);
  mkdirSync(to, { recursive: true });
  for (const f of readdirSync(from)) {
    copyFileSync(join(from, f), join(to, f === 'result.md' ? 'index.md' : f));
  }
  console.log(`Published ${date} (${readdirSync(from).length} files)`);
}

/** First sentence-ish summary: the "×a to ×b" gain line if present. */
function summary(date: string): string {
  const md = readFileSync(join(srcDir, date, 'result.md'), 'utf8');
  const m = /\*\*(×[\d,.]+ to ×[\d,.]+)\*\*/.exec(md);
  return m ? ` — Typeflow ${m[1]} vs JSONata` : '';
}

const index = `---
title: Benchmarks
---

# Benchmarks

Runtime performance reports, measured on a development machine (see the
[interactive benchmark page](/benchmark) to measure in your own browser).
Each report is generated by \`bun run bench\` and published here by
\`bun run bench:publish\`.

${runs.map((date) => `- [${date}](./${date}/)${summary(date)}`).join('\n')}
`;

writeFileSync(join(outDir, 'index.md'), index);
console.log(
  `Index written: ${join(outDir, 'index.md')} (${runs.length} run${runs.length > 1 ? 's' : ''})`,
);
